### ISSUE TITLE
Polynomial Regression - Lab

### ISSUE THREAD

**Issue by deannagould** [learn-co-curriculum/dsc-polynomial-regression-lab-v2-5#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5599/assignments/196924?module_item_id=443499

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X ] Instructions unclear
- [ X] Other (explain below)
lab is pulling up weird, has one cell with a few lines of code in it but no instructions
### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk
- [X] Saturn

**Comment by jessepisel** [comment]
@deannagould Thanks for opening this issue 👋 . We are looking into this issue at this time. If you could try [this link](https://app.flatironschool.saturnenterprise.io/dash/resources?workspacePath=notebooks%2Fworkspace%2Fflatiron-curriculum%2FPhase2%2Fdsc-polynomial-regression-lab-v2-5%2Findex.ipynb&apply=true&recipe=%7B%0A++%22name%22%3A+%22ds-course-phase2%22%2C%0A++%22image%22%3A+%7B%0A++++%22name%22%3A+%22flatiron-school%22%2C%0A++++%22version%22%3A+%222022.10.11%22%2C%0A++++%22owner%22%3A+%22production%22%0A++%7D%2C%0A++%22description%22%3A+%22%22%2C%0A++%22environment_variables%22%3A+%7B%7D%2C%0A++%22working_directory%22%3A+%22%2Fhome%2Fjovyan%2Fworkspace%22%2C%0A++%22start_script%22%3A+%22mkdir+-p+%2Fhome%2Fjovyan%2Fflatiron-curriculum-clone%5Cnmkdir+-p+%2Fhome%2Fjovyan%2Fworkspace%2Fflatiron-curriculum%5Cnaws+s3+sync+s3%3A%2F%2Fflatiron-curriculum%2FPhase2+%2Fhome%2Fjovyan%2Fflatiron-curriculum-clone%2FPhase2+--no-sign-request%5Cncp+-rn+%2Fhome%2Fjovyan%2Fflatiron-curriculum-clone%2F%2A+%2Fhome%2Fjovyan%2Fworkspace%2Fflatiron-curriculum%2F%5Cn%22%2C%0A++%22git_repositories%22%3A+%5B%5D%2C%0A++%22secrets%22%3A+%5B%5D%2C%0A++%22jupyter_server%22%3A+%7B%0A++++%22instance_type%22%3A+%22large%22%2C%0A++++%22disk_space%22%3A+%2210Gi%22%2C%0A++++%22auto_shutoff%22%3A+%221+hour%22%2C%0A++++%22start_ssh%22%3A+false%2C%0A++++%22use_spot_instance%22%3A+false%2C%0A++++%22start_dind%22%3A+false%2C%0A++++%22self_destruct%22%3A+false%2C%0A++++%22status%22%3A+%22running%22%0A++%7D%2C%0A++%22visibility%22%3A+%22owner%22%2C%0A++%22schema_version%22%3A+%222022.08.01%22%0A%7D%0A) it should open the correct notebook for this lab on SaturnCloud.

**Comment by jessepisel** [comment]
This lab has been fixed in Canvas, the SaturnCloud button now opens the correct notebook. 

I am closing this issue at this time.
